"""
SORT-tendance :: src/core/gating_opt.py

Production-grade State Machine Gating Engine.

Responsibilities:
  1. Maintain the global RAM-resident container `attendance_final_log`
     that securely binds active track IDs to verified student records
     or localized stranger classifications.
  2. Enforce Strict State Labeling & Gating Cascades across three
     deterministic states:
       * VERIFIED STUDENT -- live face similarity clears the matching
         threshold (0.60 - 0.65 adaptive). Push the resolved
         "[NRP / Student Name]" label to the bounding box, fire a
         single secure log transaction, flag the track as low-priority,
         and PERMANENTLY suspend all face scanning / extraction /
         Re-ID for that track ID.
       * STRANGER_XX -- person bbox is maintained but face metrics
         continuously fall below the floor (< 0.60). Query the track's
         body-reid vector against Index Instance 2 (Dynamic Appearance
         Cache). If a match clears appearance_inherit_threshold
         (>= 0.65), inherit the existing tracking number. Otherwise
         increment the sequential counter, register the vector, and
         lock the label. Once flagged as a Stranger, ALL facial
         scanning is fully terminated -- reliance shifts purely to
         backend spatial coordinate tracking.
       * ANOMALY -- face elements are detected WITHOUT a corresponding
         body bounding box. Intercept, label strictly as "[ANOMALY]",
         bypass standard tracking logic, and force the throttle
         controller into BURST mode to prevent data loss.
  3. Deterministic BBox Timestamping Layer -- for every transaction,
     extract the exact hardware frame index timestamp at the microsecond
     the bounding box was generated, decoupling logging chronologies
     from processing lag or queue latencies.

Author: SORT-tendance Engineering
"""

from __future__ import annotations

import os
import sys
import gc
import time
import logging
import traceback
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

# ---------------------------------------------------------------------------
# Optional dependency guards.
# ---------------------------------------------------------------------------
try:
    import cv2
    _CV2_AVAILABLE = True
except ImportError:                       # pragma: no cover
    _CV2_AVAILABLE = False
    cv2 = None  # type: ignore

# Local imports.
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
try:
    from utils.database_manager import ConfigRegistry
except ImportError:                       # pragma: no cover
    ConfigRegistry = None  # type: ignore


# ============================================================================
# Logging Configuration
# ============================================================================
logger = logging.getLogger("sortendance.gating_opt")
if not logger.handlers:
    _h = logging.StreamHandler(sys.stdout)
    _h.setFormatter(logging.Formatter(
        "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    ))
    logger.addHandler(_h)
    logger.setLevel(logging.INFO)


# ============================================================================
# Enums
# ============================================================================
class EntityState(str, Enum):
    """The three deterministic gating states."""
    PENDING = "PENDING"
    VERIFIED_STUDENT = "VERIFIED_STUDENT"
    STRANGER = "STRANGER"
    ANOMALY = "ANOMALY"


# ============================================================================
# Data Classes
# ============================================================================
@dataclass
class FrameTimestamp:
    """
    Deterministic bbox timestamp extracted from the hardware frame
    capture index marker. Decouples logging chronologies from
    processing lag / queue latencies.
    """
    frame_index: int                 # Monotonic hardware frame counter
    capture_us: int                  # Microsecond-of-epoch from the
                                     # capture thread at frame grab time.
    bbox_us: int                     # Microsecond-of-epoch at the
                                     # precise instant the bbox was
                                     # generated by the AI thread.

    def to_iso(self) -> str:
        import datetime as _dt
        return _dt.datetime.fromtimestamp(
            self.bbox_us / 1_000_000.0, tz=_dt.timezone.utc
        ).isoformat()


@dataclass
class AttendanceEntry:
    """A single record in the attendance_final_log container."""
    track_id: int
    state: EntityState
    resolved_label: str
    student_id: Optional[str]
    student_name: Optional[str]
    stranger_id: Optional[int]
    timestamp: FrameTimestamp
    bbox: Tuple[int, int, int, int]
    similarity_score: float
    locked: bool = True               # Once resolved, the entry is locked.


@dataclass
class AnomalyEntry:
    """A floating face-without-body anomaly record."""
    face_bbox: Tuple[int, int, int, int]
    timestamp: FrameTimestamp
    similarity_score: float = 0.0
    label: str = "[ANOMALY]"


@dataclass
class TrackState:
    """Per-track gating state, mirrored to IdentityMatcher.TrackInferenceState."""
    track_id: int
    state: EntityState = EntityState.PENDING
    resolved_label: str = "[PENDING]"
    student_id: Optional[str] = None
    student_name: Optional[str] = None
    stranger_id: Optional[int] = None
    face_scanning_active: bool = True
    body_reid_active: bool = True
    last_similarity: float = 0.0
    last_frame_index: int = -1
    # Pending stranger-evaluation frames counter. We require the face
    # metric to stay below the floor for a small window before locking
    # the stranger label, to avoid spurious locks during brief occlusions.
    stranger_pending_frames: int = 0
    # TTFM anchor: microsecond timestamp of this track's first sighting.
    first_seen_us: Optional[int] = None


# ============================================================================
# Gating Engine
# ============================================================================
class GatingEngine:
    """
    State Machine Gating Engine.

    Owns:
      * `attendance_final_log` -- the global RAM-resident container that
        binds track IDs to verified student records or stranger labels.
      * `anomaly_log` -- the list of intercepted face-without-body
        anomalies.
      * Per-track `TrackState` registry.

    Public API for the orchestrator:
        gate = GatingEngine(config, identity_matcher, res_opt_engine,
                            async_logger, video_recorder)
        gate.initialize()
        decision = gate.evaluate_track(track_id, frame_ts, ...)
        gate.evaluate_anomaly(face_bbox, frame_ts)
        gate.shutdown()
    """

    # Patch 30 :: The number of consecutive sub-threshold frames
    # required before a track is locked as a Stranger. This prevents
    # transient flicker during partial occlusions from mislabeling a
    # verified student. Was hard-coded to 3; now read from
    # config.yaml -> gating.stranger.pending_threshold (default 8).
    # The class attribute is kept as a fallback for backward compat
    # with code that still references gate.STRANGER_PENDING_THRESHOLD
    # (e.g. the selftest at the bottom of this file).
    # Patch 58 :: Class fallback raised from 8 -> 30 to match the
    # config default (config.yaml: stranger.pending_threshold = 30).
    # This fallback is only used if the config key is missing; the
    # live value is read from config in __init__.
    STRANGER_PENDING_THRESHOLD: int = 30

    # The number of frames to force BURST mode for when an ANOMALY is
    # intercepted.
    ANOMALY_BURST_FRAME_WINDOW: int = 30

    # ------------------------------------------------------------------
    def __init__(
        self,
        config: Optional[Dict[str, Any]] = None,
        identity_matcher: Optional[Any] = None,
        res_opt_engine: Optional[Any] = None,
        async_logger: Optional[Any] = None,
        video_recorder: Optional[Any] = None,
    ) -> None:
        self.config: Dict[str, Any] = (
            config or (ConfigRegistry.load() if ConfigRegistry else {})
        )

        gcfg = self.config["gating"]
        self.sim_baseline: float = float(
            gcfg["verified_student"]["similarity_baseline"]
        )
        self.sim_dynamic_floor: float = float(
            gcfg["verified_student"]["similarity_dynamic_floor"]
        )
        self.stranger_floor: float = float(
            gcfg["stranger"]["similarity_floor"]
        )
        self.appearance_inherit_threshold: float = float(
            gcfg["stranger"]["appearance_inherit_threshold"]
        )
        # Patch 30 :: Read the stranger pending threshold from config.
        # Falls back to 8 (the new class-attr default) if the field is
        # absent -- this maintains backward compat with older
        # config.yaml files that haven't been regenerated.
        self.stranger_pending_threshold: int = int(
            gcfg["stranger"].get("pending_threshold", 8)
        )
        # Patch 37 :: YOLO confidence gates for stranger operations.
        self.snapshot_min_yolo_conf: float = float(
            gcfg["stranger"].get("snapshot_min_yolo_conf", 0.50)
        )
        self.reid_min_yolo_conf: float = float(
            gcfg["stranger"].get("reid_min_yolo_conf", 0.50)
        )
        self.anomaly_label: str = str(gcfg["anomaly"]["label"])
        self.anomaly_force_burst: bool = bool(
            gcfg["anomaly"]["force_burst_mode"]
        )
        self.anomaly_log_to_csv: bool = bool(gcfg["anomaly"]["log_to_csv"])
        self.freeze_verified: bool = bool(
            self.config["main"]["freeze_verified_tracks"]
        )
        self.freeze_stranger: bool = bool(
            self.config["main"]["freeze_stranger_tracks"]
        )

        # External engine references (set in initialize()).
        self.identity_matcher = identity_matcher
        self.res_opt_engine = res_opt_engine
        self.async_logger = async_logger
        self.video_recorder = video_recorder

        # The global RAM-resident containers.
        self.attendance_final_log: Dict[int, AttendanceEntry] = {}
        self.anomaly_log: List[AnomalyEntry] = []
        self._track_states: Dict[int, TrackState] = {}

        # Persistent NRP-level state -- decouples verified student
        # identities from active track IDs so that track ID swaps (due
        # to bbox scale expansion near the lens) inherit the prior
        # verified status via body-Re-ID matching.
        # Key: student_id, Value: last resolved track_id + label.
        self.verified_nrp_state: Dict[str, Dict[str, Any]] = {}

        self._initialized: bool = False

    # ==================================================================
    # Lifecycle.
    # ==================================================================
    def initialize(self) -> None:
        """
        Wire up the external engine references. This is intentionally
        separated from __init__ so that the orchestrator can construct
        all engines first, then wire them in a second pass.
        """
        if self._initialized:
            logger.warning("GatingEngine already initialized; skipping.")
            return

        logger.info(
            "GatingEngine initializing | sim_baseline=%.2f | sim_floor=%.2f | "
            "stranger_floor=%.2f | appearance_inherit=%.2f | "
            "stranger_pending_threshold=%d | "
            "snapshot_min_yolo_conf=%.2f | reid_min_yolo_conf=%.2f",
            self.sim_baseline, self.sim_dynamic_floor,
            self.stranger_floor, self.appearance_inherit_threshold,
            self.stranger_pending_threshold,
            self.snapshot_min_yolo_conf, self.reid_min_yolo_conf,
        )
        self._initialized = True

    # ------------------------------------------------------------------
    def _ensure_track_state(self, track_id: int) -> TrackState:
        state = self._track_states.get(track_id)
        if state is None:
            state = TrackState(track_id=track_id)
            self._track_states[track_id] = state
        return state

    # ==================================================================
    # Deterministic BBox Timestamping Layer.
    # ==================================================================
    @staticmethod
    def make_frame_timestamp(
        frame_index: int,
        capture_us: Optional[int] = None,
    ) -> FrameTimestamp:
        """
        Build a deterministic FrameTimestamp from the hardware frame
        capture index marker.

        Args:
            frame_index: Monotonic hardware frame counter (from the
                         capture thread).
            capture_us:  Microsecond-of-epoch when the frame was grabbed
                         by the capture thread. If None, the current
                         wall-clock microsecond is used as a fallback
                         (the orchestrator should always supply the
                         hardware timestamp for full determinism).
        """
        now_us = int(time.time() * 1_000_000)
        return FrameTimestamp(
            frame_index=frame_index,
            capture_us=capture_us if capture_us is not None else now_us,
            bbox_us=now_us,
        )

    # ==================================================================
    # State 1: VERIFIED STUDENT cascade.
    # ==================================================================
    def _resolve_verified_student(
        self,
        track_id: int,
        state: TrackState,
        student_id: str,
        student_name: str,
        similarity: float,
        effective_threshold: float,
        frame_ts: FrameTimestamp,
        bbox: Tuple[int, int, int, int],
        yolo_latency_ms: float = 0.0,
        face_det_latency_ms: float = 0.0,
        arcface_latency_ms: float = 0.0,
        usearch_latency_ms: float = 0.0,
        ttfm_ms: float = 0.0,
    ) -> AttendanceEntry:
        """
        Lock the track as a VERIFIED STUDENT.

        Steps:
          1. Push the resolved "[NRP / Student Name]" label to the bbox.
          2. Fire a single secure log transaction to the async logger.
          3. Flag the track as low-priority (face scanning terminated).
          4. PERMANENTLY suspend face scanning / extraction / Re-ID
             via the identity_matcher.terminate_face_scanning(...) hook.
          5. Update the verified_nrp_state persistent map.
        """
        label = f"[{student_id} / {student_name}]"
        state.state = EntityState.VERIFIED_STUDENT
        state.resolved_label = label
        state.student_id = student_id
        state.student_name = student_name
        state.face_scanning_active = False
        state.body_reid_active = False
        state.last_similarity = float(similarity)
        state.last_frame_index = frame_ts.frame_index

        entry = AttendanceEntry(
            track_id=track_id,
            state=EntityState.VERIFIED_STUDENT,
            resolved_label=label,
            student_id=student_id,
            student_name=student_name,
            stranger_id=None,
            timestamp=frame_ts,
            bbox=bbox,
            similarity_score=float(similarity),
            locked=True,
        )
        self.attendance_final_log[track_id] = entry

        # Update the persistent NRP-level state for track-ID-swap
        # inheritance.
        self.verified_nrp_state[student_id] = {
            "track_id": track_id,
            "label": label,
            "student_name": student_name,
            "last_frame_index": frame_ts.frame_index,
        }

        # Fire the secure log transaction (single transaction per session).
        if self.async_logger is not None:
            try:
                self.async_logger.log_entry(
                    timestamp_us=frame_ts.bbox_us,
                    track_id=track_id,
                    resolved_label=label,
                    state=EntityState.VERIFIED_STUDENT.value,
                    similarity_score=float(similarity),
                    bbox=bbox,
                    nrp=student_id,
                    student_name=student_name,
                    frame_index=frame_ts.frame_index,
                    yolo_latency_ms=yolo_latency_ms,
                    face_det_latency_ms=face_det_latency_ms,
                    arcface_latency_ms=arcface_latency_ms,
                    usearch_latency_ms=usearch_latency_ms,
                    ttfm_ms=ttfm_ms,
                )
            except Exception as exc:
                logger.error(
                    "AsyncLogger log_entry failed for VERIFIED_STUDENT "
                    "track %d: %s", track_id, exc,
                )

        # Terminate facial scanning + Re-ID on the identity matcher.
        if self.identity_matcher is not None:
            try:
                self.identity_matcher.terminate_face_scanning(
                    track_id=track_id,
                    resolved_state=EntityState.VERIFIED_STUDENT.value,
                    resolved_label=label,
                    resolved_student_id=student_id,
                    resolved_stranger_id=None,
                    keep_body_reid=False,
                )
            except Exception as exc:
                logger.error(
                    "IdentityMatcher.terminate_face_scanning failed for "
                    "VERIFIED_STUDENT track %d: %s", track_id, exc,
                )

        logger.info(
            "VERIFIED_STUDENT locked | track=%d | label=%s | sim=%.3f | "
            "thr=%.2f | frame=%d",
            track_id, label, similarity, effective_threshold,
            frame_ts.frame_index,
        )
        return entry

    # ==================================================================
    # State 2: STRANGER_XX cascade.
    # ==================================================================
    def _resolve_stranger(
        self,
        track_id: int,
        state: TrackState,
        body_feature: Optional[np.ndarray],
        frame_ts: FrameTimestamp,
        bbox: Tuple[int, int, int, int],
        centroid: Tuple[float, float],
        # Patch 37 :: YOLO conf gate for Re-ID. When below
        # reid_min_yolo_conf, skip cache search + registration.
        yolo_conf: float = 1.0,
        # Patch 42 :: Latency telemetry for STRANGER CSV rows.
        yolo_latency_ms: float = 0.0,
        face_det_latency_ms: float = 0.0,
        arcface_latency_ms: float = 0.0,
        usearch_latency_ms: float = 0.0,
        body_reid_latency_ms: float = 0.0,
    ) -> AttendanceEntry:
        """
        Lock the track as a STRANGER_XX.

        Steps:
          1. Query the body-reid vector against Index Instance 2.
          2. If a match clears appearance_inherit_threshold (>=0.65),
             inherit the existing stranger ID.
          3. Otherwise, increment the sequential counter and register
             the vector to Index 2.
          4. Lock the label state.
          5. CRITICAL: terminate ALL facial scanning / extraction /
             recognition for this track ID. Reliance shifts purely to
             backend spatial coordinate tracking.
        """
        stranger_id: Optional[int] = None
        label: str = "[Stranger_??]"
        inherited: bool = False

        # Patch 37 :: Gate Re-ID on YOLO confidence. When det_conf is
        # below reid_min_yolo_conf, the body appearance embedding is
        # unreliable (partial occlusion / motion blur / small bbox).
        # In this case we skip BOTH the cache search (no inheritance)
        # AND the cache registration (don't pollute the cache with a
        # noisy embedding). The track still gets locked as a stranger
        # with a new sequential ID.
        _reid_conf_ok = (yolo_conf >= self.reid_min_yolo_conf)
        if not _reid_conf_ok:
            logger.info(
                "STRANGER Re-ID skipped (low YOLO conf) | track=%d | "
                "det_conf=%.3f < threshold=%.2f -- assigning new ID, "
                "embedding NOT cached",
                track_id, yolo_conf, self.reid_min_yolo_conf,
            )

        if (
            self.identity_matcher is not None
            and body_feature is not None
            and _reid_conf_ok
        ):
            try:
                stranger_id, label, inherited = (
                    self.identity_matcher.register_stranger(
                        body_feature=body_feature,
                        timestamp_us=frame_ts.bbox_us,
                        centroid=centroid,
                    )
                )
            except Exception as exc:
                logger.error(
                    "Stranger registration failed for track %d: %s",
                    track_id, exc,
                )
                stranger_id = None
                label = "[Stranger_??]"
        elif not _reid_conf_ok:
            # Skip Re-ID entirely; fall through to the sequential ID
            # assignment below. The embedding is NOT added to the cache.
            stranger_id = None
            label = "[Stranger_??]"

        # If registration failed, assign a fallback sequential ID.
        if stranger_id is None:
            # Synthesize a sequential ID from the current stranger count.
            existing_count = sum(
                1 for e in self.attendance_final_log.values()
                if e.state == EntityState.STRANGER
            )
            stranger_id = existing_count + 1
            label = f"Stranger_{stranger_id:02d}"

        state.state = EntityState.STRANGER
        state.resolved_label = label
        state.stranger_id = stranger_id
        state.face_scanning_active = False
        # Body Re-ID remains active so the orchestrator can continue
        # tracking the stranger via spatial coordinates + appearance.
        state.body_reid_active = True
        state.last_frame_index = frame_ts.frame_index

        entry = AttendanceEntry(
            track_id=track_id,
            state=EntityState.STRANGER,
            resolved_label=label,
            student_id=None,
            student_name=None,
            stranger_id=stranger_id,
            timestamp=frame_ts,
            bbox=bbox,
            similarity_score=float(state.last_similarity),
            locked=True,
        )
        self.attendance_final_log[track_id] = entry

        # Log the stranger entry.
        if self.async_logger is not None:
            try:
                self.async_logger.log_entry(
                    timestamp_us=frame_ts.bbox_us,
                    track_id=track_id,
                    resolved_label=label,
                    state=EntityState.STRANGER.value,
                    similarity_score=float(state.last_similarity),
                    bbox=bbox,
                    frame_index=frame_ts.frame_index,
                    yolo_latency_ms=yolo_latency_ms,
                    face_det_latency_ms=face_det_latency_ms,
                    arcface_latency_ms=arcface_latency_ms,
                    usearch_latency_ms=usearch_latency_ms,
                    body_reid_latency_ms=body_reid_latency_ms,
                )
            except Exception as exc:
                logger.error(
                    "AsyncLogger log_entry failed for STRANGER track %d: %s",
                    track_id, exc,
                )

        # Terminate facial scanning on the identity matcher. Keep body
        # Re-ID active for stranger spatial tracking.
        if self.identity_matcher is not None:
            try:
                self.identity_matcher.terminate_face_scanning(
                    track_id=track_id,
                    resolved_state=EntityState.STRANGER.value,
                    resolved_label=label,
                    resolved_student_id=None,
                    resolved_stranger_id=stranger_id,
                    keep_body_reid=True,
                )
            except Exception as exc:
                logger.error(
                    "IdentityMatcher.terminate_face_scanning failed for "
                    "STRANGER track %d: %s", track_id, exc,
                )

        logger.info(
            "STRANGER locked | track=%d | label=%s | inherited=%s | frame=%d",
            track_id, label, inherited, frame_ts.frame_index,
        )
        return entry

    # ==================================================================
    # State 3: ANOMALY cascade.
    # ==================================================================
    def evaluate_anomaly(
        self,
        face_bbox: Tuple[int, int, int, int],
        frame_ts: FrameTimestamp,
        body_track_ids: List[int],
        # Patch 42 :: Latency telemetry for ANOMALY CSV rows. The
        # anomaly path bypasses body-Re-ID, so body_reid_latency_ms
        # is always 0 for ANOMALY entries.
        yolo_latency_ms: float = 0.0,
        face_det_latency_ms: float = 0.0,
        arcface_latency_ms: float = 0.0,
        usearch_latency_ms: float = 0.0,
    ) -> AnomalyEntry:
        """
        Intercept a face-without-body anomaly.

        Steps:
          1. Label the floating bbox strictly as "[ANOMALY]".
          2. Bypass standard tracking logic (no track_id assignment).
          3. Override the throttle controller to force BURST mode for
             ANOMALY_BURST_FRAME_WINDOW frames to prevent data loss.
          4. Optionally log to the CSV (per config).
        """
        entry = AnomalyEntry(
            face_bbox=face_bbox,
            timestamp=frame_ts,
            label=self.anomaly_label,
        )
        self.anomaly_log.append(entry)

        # Force BURST mode on the Resource Optimization Engine.
        if self.anomaly_force_burst and self.res_opt_engine is not None:
            try:
                self.res_opt_engine.force_burst(
                    frame_window=self.ANOMALY_BURST_FRAME_WINDOW,
                    current_frame_index=frame_ts.frame_index,
                )
            except Exception as exc:
                logger.error(
                    "Failed to force BURST for ANOMALY: %s", exc,
                )

        # Optional CSV logging.
        if self.anomaly_log_to_csv and self.async_logger is not None:
            try:
                self.async_logger.log_entry(
                    timestamp_us=frame_ts.bbox_us,
                    track_id=-1,                # ANOMALY has no track ID
                    resolved_label=self.anomaly_label,
                    state=EntityState.ANOMALY.value,
                    similarity_score=0.0,
                    bbox=face_bbox,
                    frame_index=frame_ts.frame_index,
                    yolo_latency_ms=yolo_latency_ms,
                    face_det_latency_ms=face_det_latency_ms,
                    arcface_latency_ms=arcface_latency_ms,
                    usearch_latency_ms=usearch_latency_ms,
                )
            except Exception as exc:
                logger.error(
                    "AsyncLogger log_entry failed for ANOMALY: %s", exc,
                )

        logger.warning(
            "ANOMALY intercepted | bbox=%s | frame=%d | body_tracks=%d",
            face_bbox, frame_ts.frame_index, len(body_track_ids),
        )
        return entry

    # ==================================================================
    # Top-level track evaluator.
    # ==================================================================
    def evaluate_track(
        self,
        track_id: int,
        frame_ts: FrameTimestamp,
        bbox: Tuple[int, int, int, int],
        centroid: Tuple[float, float],
        face_similarity: float,
        best_student_id: Optional[str],
        best_student_name: Optional[str],
        body_feature: Optional[np.ndarray],
        effective_threshold: Optional[float] = None,
        ema_score: Optional[float] = None,
        ema_cluster_size: int = 0,
        yolo_latency_ms: float = 0.0,
        face_det_latency_ms: float = 0.0,
        arcface_latency_ms: float = 0.0,
        usearch_latency_ms: float = 0.0,
        # Patch 42 :: OSNet body Re-ID inference latency (per-frame batch).
        body_reid_latency_ms: float = 0.0,
        # Patch 37 :: YOLO detection confidence for this track, used
        # to gate stranger Re-ID inheritance + cache registration.
        # When det_conf < reid_min_yolo_conf, the body appearance
        # embedding is considered unreliable and is NOT used for
        # matching or memorizing. The track still gets locked as a
        # stranger, but with a new ID and no cache entry.
        yolo_conf: float = 1.0,
    ) -> TrackState:
        """
        Evaluate a single track against the three-state cascade.

        Decision tree:
          1. If the track is already locked (VERIFIED_STUDENT or
             STRANGER), short-circuit and return the existing state.
          2. Compute the effective threshold:
                * Caller-supplied threshold (from the Adaptive TTFM
                  Tracker) if provided.
                * Else, fall back to sim_baseline (0.65).
          3. If face_similarity >= effective_threshold AND (ema_score
             is None OR (ema_score >= 0.62 AND ema_cluster_size >= 4)):
             -> Resolve as VERIFIED_STUDENT.
          4. Else if face_similarity < stranger_floor (0.60) for
             STRANGER_PENDING_THRESHOLD consecutive frames:
             -> Resolve as STRANGER_XX via Index Instance 2.
          5. Else: remain PENDING.

        Returns the updated TrackState.
        """
        state = self._ensure_track_state(track_id)
        # Stamp track birth time for TTFM (only on first sighting).
        if getattr(state, "first_seen_us", None) is None:
            state.first_seen_us = frame_ts.bbox_us

        # Short-circuit if already locked.
        if state.state == EntityState.VERIFIED_STUDENT:
            return state
        if state.state == EntityState.STRANGER and self.freeze_stranger:
            return state

        # Update similarity + frame index on the state.
        state.last_similarity = float(face_similarity)
        state.last_frame_index = frame_ts.frame_index

        # Resolve the effective threshold.
        if effective_threshold is None:
            effective_threshold = self.sim_baseline
        effective_threshold = float(effective_threshold)

        # --- State 1: VERIFIED STUDENT -------------------------------
        ema_clears: bool = True
        if ema_score is not None:
            ema_clears = (
                float(ema_score) >= 0.62
                and int(ema_cluster_size) >= 4
            )

        if (
            face_similarity >= effective_threshold
            and best_student_id is not None
            and ema_clears
        ):
            # Compute TTFM: from track birth (first_seen_us) to now (bbox_us).
            ttfm_ms = 0.0
            first_seen = getattr(state, "first_seen_us", None)
            if first_seen is not None:
                ttfm_ms = (frame_ts.bbox_us - first_seen) / 1000.0

            self._resolve_verified_student(
                track_id=track_id,
                state=state,
                student_id=best_student_id,
                student_name=(
                    best_student_name
                    if best_student_name is not None
                    else best_student_id
                ),
                similarity=face_similarity,
                effective_threshold=effective_threshold,
                frame_ts=frame_ts,
                bbox=bbox,
                yolo_latency_ms=yolo_latency_ms,
                face_det_latency_ms=face_det_latency_ms,
                arcface_latency_ms=arcface_latency_ms,
                usearch_latency_ms=usearch_latency_ms,
                ttfm_ms=ttfm_ms,
            )
            return state

        # --- State 2: STRANGER ---------------------------------------
        if face_similarity < self.stranger_floor:
            state.stranger_pending_frames += 1
            # Patch 30 :: use the config-driven instance attribute
            # (self.stranger_pending_threshold) instead of the
            # hard-coded class attribute (STRANGER_PENDING_THRESHOLD).
            if state.stranger_pending_frames >= self.stranger_pending_threshold:
                self._resolve_stranger(
                    track_id=track_id,
                    state=state,
                    body_feature=body_feature,
                    frame_ts=frame_ts,
                    bbox=bbox,
                    centroid=centroid,
                    yolo_conf=yolo_conf,
                    yolo_latency_ms=yolo_latency_ms,
                    face_det_latency_ms=face_det_latency_ms,
                    arcface_latency_ms=arcface_latency_ms,
                    usearch_latency_ms=usearch_latency_ms,
                    body_reid_latency_ms=body_reid_latency_ms,
                )
                return state
        else:
            # Reset the stranger pending counter if we got a non-floor
            # hit (prevents spurious locks during brief occlusions).
            state.stranger_pending_frames = 0

        # --- Default: remain PENDING ---------------------------------
        return state

    # ==================================================================
    # Body-Re-ID inheritance (track-ID swap recovery).
    # ==================================================================
    def inherit_verified_state(
        self,
        new_track_id: int,
        body_reid_result: Optional[Any],
        frame_ts: FrameTimestamp,
        bbox: Tuple[int, int, int, int],
    ) -> bool:
        """
        Attempt to inherit a VERIFIED_STUDENT label from a prior track
        ID via body-Re-ID matching. Used when a tracked student
        approaches the camera and the bbox scale expansion drops the
        tracking connection, generating a new track ID.

        Args:
            new_track_id:      The newly generated track ID.
            body_reid_result:  A BodyReIDResult from the identity matcher
                               (or None).
            frame_ts:          Deterministic frame timestamp.
            bbox:              Current bbox of the new track.

        Returns True if inheritance was applied.
        """
        if body_reid_result is None or not body_reid_result.inheritance_applied:
            return False

        matched_track_id = body_reid_result.matched_track_id
        prior_entry = self.attendance_final_log.get(matched_track_id)
        if prior_entry is None or prior_entry.state != EntityState.VERIFIED_STUDENT:
            return False

        state = self._ensure_track_state(new_track_id)
        state.state = EntityState.VERIFIED_STUDENT
        state.resolved_label = prior_entry.resolved_label
        state.student_id = prior_entry.student_id
        state.student_name = prior_entry.student_name
        state.face_scanning_active = False
        state.body_reid_active = False
        state.last_frame_index = frame_ts.frame_index

        new_entry = AttendanceEntry(
            track_id=new_track_id,
            state=EntityState.VERIFIED_STUDENT,
            resolved_label=prior_entry.resolved_label,
            student_id=prior_entry.student_id,
            student_name=prior_entry.student_name,
            stranger_id=None,
            timestamp=frame_ts,
            bbox=bbox,
            similarity_score=float(body_reid_result.body_similarity),
            locked=True,
        )
        self.attendance_final_log[new_track_id] = new_entry

        # Update the persistent NRP state to point at the new track ID.
        if prior_entry.student_id is not None:
            self.verified_nrp_state[prior_entry.student_id] = {
                "track_id": new_track_id,
                "label": prior_entry.resolved_label,
                "student_name": prior_entry.student_name,
                "last_frame_index": frame_ts.frame_index,
            }

        # Terminate facial scanning on the new track via the identity matcher.
        if self.identity_matcher is not None:
            try:
                self.identity_matcher.terminate_face_scanning(
                    track_id=new_track_id,
                    resolved_state=EntityState.VERIFIED_STUDENT.value,
                    resolved_label=prior_entry.resolved_label,
                    resolved_student_id=prior_entry.student_id,
                    resolved_stranger_id=None,
                    keep_body_reid=False,
                )
            except Exception as exc:
                logger.error(
                    "IdentityMatcher.terminate_face_scanning failed during "
                    "verified-state inheritance for track %d: %s",
                    new_track_id, exc,
                )

        logger.info(
            "Verified state inherited | new_track=%d | from_track=%d | "
            "label=%s | frame=%d",
            new_track_id, matched_track_id, prior_entry.resolved_label,
            frame_ts.frame_index,
        )
        return True

    # ==================================================================
    # Read-only views for the orchestrator / dashboard.
    # ==================================================================
    def get_resolved_label(self, track_id: int) -> str:
        """Return the resolved label for a track, or '[PENDING]'."""
        entry = self.attendance_final_log.get(track_id)
        if entry is not None:
            return entry.resolved_label
        state = self._track_states.get(track_id)
        if state is not None:
            return state.resolved_label
        return "[PENDING]"

    # ------------------------------------------------------------------
    def is_track_locked(self, track_id: int) -> bool:
        """True if the track has been resolved to any non-PENDING state."""
        state = self._track_states.get(track_id)
        if state is None:
            return False
        return state.state != EntityState.PENDING

    # ------------------------------------------------------------------
    def is_face_scanning_active(self, track_id: int) -> bool:
        state = self._track_states.get(track_id)
        if state is None:
            return True
        return state.face_scanning_active

    # ------------------------------------------------------------------
    def drop_track(self, track_id: int) -> None:
        """
        Drop a track that has exited the frame. The attendance_final_log
        entry is PRESERVED (it is the audit record); only the active
        TrackState is purged.
        """
        self._track_states.pop(track_id, None)

    # ------------------------------------------------------------------
    def all_attendance_entries(self) -> List[AttendanceEntry]:
        return list(self.attendance_final_log.values())

    # ------------------------------------------------------------------
    def all_anomaly_entries(self) -> List[AnomalyEntry]:
        return list(self.anomaly_log)

    # ------------------------------------------------------------------
    def telemetry(self) -> Dict[str, Any]:
        return {
            "verified_count": sum(
                1 for e in self.attendance_final_log.values()
                if e.state == EntityState.VERIFIED_STUDENT
            ),
            "stranger_count": sum(
                1 for e in self.attendance_final_log.values()
                if e.state == EntityState.STRANGER
            ),
            "anomaly_count": len(self.anomaly_log),
            "pending_track_count": sum(
                1 for s in self._track_states.values()
                if s.state == EntityState.PENDING
            ),
            "active_track_count": len(self._track_states),
            "verified_nrp_state_count": len(self.verified_nrp_state),
        }

    # ==================================================================
    # Shutdown.
    # ==================================================================
    def shutdown(self) -> None:
        """Release all per-track state. Preserve the audit log on disk
        via the async_logger's flush routine (called by the orchestrator
        before shutdown)."""
        self._track_states.clear()
        self.verified_nrp_state.clear()
        # NOTE: attendance_final_log and anomaly_log are intentionally
        # NOT cleared here -- they are the audit records and may be
        # consumed by the dashboard after the orchestrator shuts down.
        gc.collect()
        logger.info(
            "GatingEngine shut down | attendance_entries=%d | anomalies=%d",
            len(self.attendance_final_log), len(self.anomaly_log),
        )


# ============================================================================
# Module Entry Point
# ============================================================================
def _self_test() -> None:
    """Lightweight self-test harness (no external engine dependencies)."""
    logging.basicConfig(level=logging.INFO)
    logger.info("=== SORT-tendance gating_opt self-test ===")

    cfg = ConfigRegistry.load("config/config.yaml") if ConfigRegistry else {}
    gate = GatingEngine(config=cfg)
    gate.initialize()

    # --- State 1: VERIFIED STUDENT ---
    ts = gate.make_frame_timestamp(frame_index=1, capture_us=1_700_000_000_000_000)
    state = gate.evaluate_track(
        track_id=10,
        frame_ts=ts,
        bbox=(100, 100, 200, 200),
        centroid=(150.0, 150.0),
        face_similarity=0.72,
        best_student_id="2024001",
        best_student_name="John Doe",
        body_feature=None,
        effective_threshold=0.65,
        ema_score=0.70,
        ema_cluster_size=5,
    )
    logger.info(
        "Track 10 -> state=%s label=%s",
        state.state.value, state.resolved_label,
    )

    # --- State 2: STRANGER ---
    rng = np.random.default_rng(0)
    body_feat = rng.normal(0, 1, size=(512,)).astype(np.float32)
    body_feat /= np.linalg.norm(body_feat)
    ts2 = gate.make_frame_timestamp(frame_index=2, capture_us=1_700_000_000_001_000)
    for _ in range(gate.STRANGER_PENDING_THRESHOLD):
        state2 = gate.evaluate_track(
            track_id=11,
            frame_ts=ts2,
            bbox=(300, 100, 400, 200),
            centroid=(350.0, 150.0),
            face_similarity=0.30,
            best_student_id=None,
            best_student_name=None,
            body_feature=body_feat,
        )
    logger.info(
        "Track 11 -> state=%s label=%s",
        state2.state.value, state2.resolved_label,
    )

    # --- State 3: ANOMALY ---
    ts3 = gate.make_frame_timestamp(frame_index=3, capture_us=1_700_000_000_002_000)
    anomaly = gate.evaluate_anomaly(
        face_bbox=(500, 50, 540, 90),
        frame_ts=ts3,
        body_track_ids=[],
    )
    logger.info(
        "Anomaly -> label=%s frame=%d", anomaly.label, anomaly.timestamp.frame_index,
    )

    telemetry = gate.telemetry()
    logger.info("Telemetry: %s", telemetry)
    gate.shutdown()
    logger.info("=== self-test complete ===")


if __name__ == "__main__":
    _self_test()